- Isabelle/Chi_Calculus/Proper_Weak_Transition_System.thy
This adds the core laws of the proper weak transition system together with fake proofs.
> Add skeletons of proper weak core laws

- Isabelle/Chi_Calculus_Examples/Relaying.thy
The idea of this PR is to introduce some core laws related to `unidirectional_link`'s and `bidirectional_link`'s that are helpful in developing a useful theory of relaying networks.
> Introduce core laws for links in relaying networks

- Isabelle/Chi_Calculus/Basic_Transition_System.thy
- Isabelle/Chi_Calculus/Basic_Weak_Transition_System.thy
- Isabelle/Chi_Calculus/Proper_Transition_System.thy
- Isabelle/Chi_Calculus/Proper_Weak_Transition_System.thy
> Recover the more meaningful names for lift operators and associated rules

- Isabelle/Chi_Calculus/Communication.thy
- Isabelle/Chi_Calculus_Examples/Diamond.thy
> Replace `loss_and_duplication` by `duploss`

- Isabelle/Chi_Calculus_Examples/Diamond.thy
- Isabelle/Chi_Calculus_Examples/Relaying.thy
> Replace `link` by `bridge`

- Isabelle/Chi_Calculus/ROOT
- Isabelle/Chi_Calculus/Relaying.thy
- Isabelle/Chi_Calculus_Examples/Diamond.thy
- Isabelle/Chi_Calculus_Examples/ROOT
> Move bridge support to the `Chi_Calculus` session

- Isabelle/Transition_Systems/Simulation_Systems.thy
> Improve documentation of `in_bisimilarity_standard`

- Isabelle/Chi_Calculus/Basic_Transition_System.thy
- Isabelle/Chi_Calculus/Proper_Transition_System.thy
- Isabelle/Transition_Systems/Simulation_Systems.thy
- Isabelle/Transition_Systems/Weak_Transition_Systems.thy
> Purge `bisimilarity_standard`

- Isabelle/Chi_Calculus/Basic_Transition_System.thy
> Switch to simpler proof methods

- Isabelle/Chi_Calculus/Communication.thy
> Add skeletons of `multi_receive` core lemmas

- Isabelle/Chi_Calculus/Communication.thy
> Add skeletons of `duploss` core lemmas

- Isabelle/Chi_Calculus/Relaying.thy
> Add skeletons of `unidirectional_bridge` core lemmas

- Isabelle/Chi_Calculus/Processes.thy
> Add support for multiple parallel composition

- Isabelle/Chi_Calculus/Relaying.thy
> Add skeleton of distributor support

- Isabelle/Chi_Calculus/Relaying.thy
> Fix typo in name of `bidirectional_bridge_commutativity` lemma

- Isabelle/Chi_Calculus_Examples/Diamond.thy
> Formally prove the actual relaying–broadcasting equivalence theorem

- Isabelle/Chi_Calculus/Basic_Transition_System.thy
> Correct the comment about `old_bisimilarity_standard`

- Isabelle/Chi_Calculus/Relaying.thy
> Add a skeleton of lemma `sidetrack_addition`

- Isabelle/Chi_Calculus/Relaying.thy
> Generalize the `shortcut_addition` lemma

- Isabelle/Utilities/Equivalences.thy
- Isabelle/Utilities/ROOT
> Add simplifier support for equivalence reasoning

- Isabelle/Chi_Calculus/Relaying.thy
- Isabelle/Chi_Calculus_Examples/Diamond.thy
> Separate the loss servers from the bridges in `distributor_split`

- Isabelle/Utilities/Equivalences.thy
> Make the simplifier support for equivalence reasoning treat compatibility rules correctly

- Isabelle/Chi_Calculus/Basic_Transition_System.thy
- Isabelle/Chi_Calculus/Basic_Weak_Transition_System.thy
- Isabelle/Chi_Calculus/Communication.thy
- Isabelle/Chi_Calculus/Processes.thy
- Isabelle/Chi_Calculus/Proper_Transition_System.thy
- Isabelle/Chi_Calculus/Proper_Weak_Transition_System.thy
- Isabelle/Transition_Systems/Transition_Systems.thy
> Set up the equivalence simplifier to work with the bisimilarity relations

- Isabelle/Chi_Calculus/Basic_Transition_System.thy
- Isabelle/Chi_Calculus/Proper_Transition_System.thy
- Isabelle/Chi_Calculus_Examples/Diamond.thy
- Isabelle/Transition_Systems/Simulation_Systems.thy
- Isabelle/Transition_Systems/Transition_Systems.thy
> Make `bisimilarity` a defined entity

- Isabelle/Chi_Calculus/Basic_Transition_System.thy
- Isabelle/Chi_Calculus/Basic_Weak_Transition_System.thy
- Isabelle/Chi_Calculus/Communication.thy
- Isabelle/Chi_Calculus/Natural_Transition_Systems.thy
- Isabelle/Chi_Calculus/Processes.thy
- Isabelle/Chi_Calculus/Proper_Transition_System.thy
- Isabelle/Chi_Calculus/Proper_Weak_Transition_System.thy
- Isabelle/Chi_Calculus/ROOT
> Introduce locale that covers ♮-calculus transition systems

- Isabelle/Chi_Calculus/Basic_Transition_System.thy
- Isabelle/Chi_Calculus/Basic_Weak_Transition_System.thy
- Isabelle/Chi_Calculus/Communication.thy
- Isabelle/Chi_Calculus/Proper_Transition_System.thy
- Isabelle/Chi_Calculus/Proper_Weak_Transition_System.thy
- Isabelle/Utilities/Equivalences.thy
> Add support for automatic conversion of equivalences into laxer equivalences

- Isabelle/Chi_Calculus/Basic_Transition_System.thy
> Move core bisimilarities out of `equivalence`

- Isabelle/Chi_Calculus/Basic_Transition_System.thy
> Remove new-channel scope extension from `natural_simps`

- Isabelle/Chi_Calculus/Communication.thy
- Isabelle/Chi_Calculus/Relaying.thy
- Isabelle/Chi_Calculus_Examples/Diamond.thy
> Make removal of `multi_receive` duplicates a core simplification

- Isabelle/Utilities/Equivalences.thy
> Make `by equivalence` fail more quickly

- Isabelle/Chi_Calculus/Proper_Transition_System.thy
> Make scope redundancy removal a core simplification

- Isabelle/Chi_Calculus/Basic_Transition_System.thy
- Isabelle/Chi_Calculus/Basic_Weak_Transition_System.thy
- Isabelle/Chi_Calculus/Natural_Transition_Systems.thy
- Isabelle/Chi_Calculus/Processes.thy
- Isabelle/Chi_Calculus/Proper_Transition_System.thy
- Isabelle/Chi_Calculus/Proper_Weak_Transition_System.thy
> Base the `∏`-notation on a dedicated function

- Isabelle/Chi_Calculus/Natural_Transition_Systems.thy
> Remove outdated comment about `∏`-preservation

- Isabelle/Chi_Calculus/Proper_Transition_System.thy
> Move `proper_receive_scope_extension` out of `equivalence`

- Isabelle/Chi_Calculus/Core_Bisimilarities.thy
- Isabelle/Utilities/Equivalences.thy
> Add a proof method for controlled application of parallel scope extension

- Isabelle/Chi_Calculus/Basic_Transition_System.thy
- Isabelle/Chi_Calculus/Core_Bisimilarities.thy
- Isabelle/Transition_Systems/Simulation_Systems.thy
- Isabelle/Utilities/Equivalences.thy
> Add `cut` to every match pattern

- Isabelle/Chi_Calculus/Core_Bisimilarities.thy
> Add support for user-level tagged new-channel processes

- Isabelle/Chi_Calculus/Core_Bisimilarities.thy
> Change `unit` to `neutrality`

- Isabelle/Chi_Calculus/Communication.thy
- Isabelle/Chi_Calculus/Core_Bisimilarities.thy
- Isabelle/Chi_Calculus/Relaying.thy
> Remove laxer variants of core bisimilarities

- Isabelle/Chi_Calculus/Communication.thy
- Isabelle/Chi_Calculus/ROOT
- Isabelle/Chi_Calculus/Relaying.thy
- Isabelle/Chi_Calculus_Examples/Diamond.thy
> Go back to the previous definitions of bridges and unreliability servers

- Isabelle/Chi_Calculus/Communication.thy
- Isabelle/Chi_Calculus_Examples/Diamond.thy
> Swap sides of `context_localization`

- Isabelle/Chi_Calculus/Relaying.thy
- Isabelle/Chi_Calculus_Examples/Diamond.thy
> Turn `addition` lemmas into `redundancy` lemmas

- Isabelle/Chi_Calculus/Communication.thy
- Isabelle/Chi_Calculus/Relaying.thy
- Isabelle/Chi_Calculus_Examples/Diamond.thy
> Turn abbreviations for derived process operations into definitions

- .gitignore
> Remove superfluous entries from the root `.gitignore`

- Exploration/.gitignore
> Add `Exploration/.gitignore` covering LaTeX intermediate files

- Isabelle/Chi_Calculus/Communication.thy
- Isabelle/Chi_Calculus_Examples/Diamond.thy
> Base the definitions of bridges and unreliability servers on distributors

- Isabelle/Chi_Calculus/Communication.thy
> Add idempotency laws for derived communication constructs

- Isabelle/Chi_Calculus/Communication.thy
- Isabelle/Chi_Calculus/Processes.thy
- Isabelle/Chi_Calculus_Examples/Diamond.thy
> Overhaul the communication-related code

- Isabelle/Chi_Calculus/Communication.thy
> Add skeletons of `multi_receive` compatibility lemmas

- Isabelle/Chi_Calculus/Communication.thy
> Add inner forward/backward bridge redundancy lemmas

- Isabelle/Chi_Calculus/Communication.thy
> Remove inner forward/backward bridge redundancy lemmas

- Isabelle/Chi_Calculus/Basic_Transition_System.thy
- Isabelle/Chi_Calculus/Communication.thy
- Isabelle/Chi_Calculus/Core_Bisimilarities.thy
- Isabelle/Chi_Calculus/Processes.thy
- Isabelle/Chi_Calculus/Typed_Basic_Transition_System.thy
- Isabelle/Chi_Calculus/Typed_Processes.thy
- Isabelle/Chi_Calculus/binder_preservation.ML
> Make sure that binding structures are always printed with binder syntax

- Isabelle/Chi_Calculus/Basic_Transition_System.thy
- Isabelle/Chi_Calculus/Basic_Weak_Transition_System.thy
- Isabelle/Chi_Calculus/Proper_Transition_System.thy
- Isabelle/Chi_Calculus/Proper_Weak_Transition_System.thy
- Isabelle/Chi_Calculus/Typed_Basic_Transition_System.thy
- Isabelle/Chi_Calculus/Typed_Proper_Transition_System.thy
> Make types of `lift` operations and `silent` relations more general

- Isabelle/Chi_Calculus/Basic_Weak_Transition_System.thy
- Isabelle/Chi_Calculus/Proper_Weak_Transition_System.thy
> Add infix notation for the concrete weak transition relations

- Isabelle/Chi_Calculus_Examples/Relaying_Broadcasting_Equivalence.thy
> Remove extra trailing spaces in `send_interfacing_collapse`

- Isabelle/README.md
> Switch to Isabelle2019

- Isabelle/Chi_Calculus/Basic_Transition_System.thy
- Isabelle/Chi_Calculus/Basic_Weak_Transition_System.thy
- Isabelle/Chi_Calculus/Communication.thy
- Isabelle/Chi_Calculus/Core_Bisimilarities.thy
- Isabelle/Chi_Calculus/Processes.thy
- Isabelle/Chi_Calculus/Proper_Transition_System.thy
- Isabelle/Chi_Calculus/Proper_Weak_Transition_System.thy
- Isabelle/Chi_Calculus/Typed_Basic_Transition_System.thy
- Isabelle/Chi_Calculus/Typed_Processes.thy
- Isabelle/Chi_Calculus/Typed_Proper_Transition_System.thy
- Isabelle/Transition_Systems/Simulation_Systems.thy
- Isabelle/Transition_Systems/Transition_Systems.thy
- Isabelle/Transition_Systems/Weak_Transition_Systems.thy
> Switch to using cartouches for mixfix annotations

- Haskell/Makefile
- Haskell/chi-calculus-examples/chi-calculus-examples.cabal
- Haskell/chi-calculus/chi-calculus.cabal
- Haskell/fixed-length-lists/fixed-length-lists.cabal
> Update Haskell software to use newer tools

- Isabelle/Relation_Methods/Equivalence.thy
> Switch to standard method for turning chained facts into goal premises

- Isabelle/Relation_Methods/Equivalence.thy
> Amend the documentation of `equivalence`

- Isabelle/Relation_Methods/Equivalence.thy
> Make use of `symmetric` in the implementation of `equivalence`

- Isabelle/Relation_Methods/Equivalence.thy
> Remove errornous note about transfer of premises failing

- Isabelle/Relation_Methods/Equivalence.thy
- Isabelle/Relation_Methods/Monotonicity.thy
> Switch to standard naming for relations

- Isabelle/Relation_Methods/Equivalence.thy
> Replace `match` fallbacks by `?`-invocations

- Isabelle/Relation_Methods/Equivalence.thy
> Switch to condensed layout for `match` invocations with single alternatives

- Isabelle/Relation_Methods/Equivalence.thy
> Remove references to processes in `Equivalence`

- README.md
> Add top-level `README.md`

- README.md
> Improve the wording of `README.md`

- README.md
> Change `main` to `master` in `README.md`

- Isabelle/ROOTS
- Isabelle/Thorn_Calculus/ROOT
- Isabelle/Thorn_Calculus/Thorn_Calculus-Actions.thy
- Isabelle/Thorn_Calculus/Thorn_Calculus-Core_Bisimilarities.thy
- Isabelle/Thorn_Calculus/Thorn_Calculus-Experiments.thy
- Isabelle/Thorn_Calculus/Thorn_Calculus-Foundations.thy
- Isabelle/Thorn_Calculus/Thorn_Calculus-Processes.thy
- Isabelle/Thorn_Calculus/Thorn_Calculus-Semantics-Asynchronous.thy
- Isabelle/Thorn_Calculus/Thorn_Calculus-Semantics-Synchronous.thy
- Isabelle/Thorn_Calculus/binder_preservation.ML
- Isabelle/Thorn_Calculus/document/root.tex
- Isabelle/Transition_Systems-New/ROOT
- Isabelle/Transition_Systems-New/Transition_Systems-Foundations.thy
- Isabelle/Transition_Systems-New/Transition_Systems-Mutation_Systems.thy
- Isabelle/Transition_Systems-New/Transition_Systems-Simulation_Systems.thy
- Isabelle/Transition_Systems-New/Transition_Systems-Transition_Systems.thy
- Isabelle/Transition_Systems-New/Transition_Systems-Weak_Mutation_Systems.thy
- Isabelle/Transition_Systems-New/Transition_Systems-Weak_Transition_Systems.thy
- Isabelle/Transition_Systems-New/document/root.tex
> Add `Transition_Systems-New` and `Thorn_Calculus`

- Isabelle/Thorn_Calculus/Thorn_Calculus-Processes.thy
> Make primitive process family combinators friends

- Isabelle/Thorn_Calculus/Thorn_Calculus-Core_Bisimilarities.thy
- Isabelle/Thorn_Calculus/Thorn_Calculus-Processes.thy
- Isabelle/Thorn_Calculus/Thorn_Calculus-Semantics-Synchronous.thy
- Isabelle/Transition_Systems-New/Transition_Systems-Weak_Transition_Systems.thy
> Fix small issues in the implementation of the Þ-calculus

- Isabelle/Thorn_Calculus/ROOT
- Isabelle/Thorn_Calculus/Thorn_Calculus-Communication.thy
- Isabelle/Thorn_Calculus/Thorn_Calculus-Processes.thy
This will ultimately resolve #234.
> Add `Thorn_Calculus-Communication`

- Isabelle/Chi_Calculus/Basic_Transition_System.thy
- Isabelle/Chi_Calculus/Core_Bisimilarities.thy
- Isabelle/Chi_Calculus/Typed_Basic_Transition_System.thy
- Isabelle/Thorn_Calculus/Thorn_Calculus-Core_Bisimilarities.thy
- Isabelle/Thorn_Calculus/Thorn_Calculus-Experiments.thy
- Isabelle/Thorn_Calculus/Thorn_Calculus-Semantics-Synchronous.thy
- Isabelle/Transition_Systems-New/Transition_Systems-Simulation_Systems.thy
> Switch to Isabelle2021-1

- Isabelle/Relation_Methods/ROOT
- Isabelle/Thorn_Calculus/ROOT
- Isabelle/Thorn_Calculus/Thorn_Calculus-Core_Bisimilarities.thy
- Isabelle/Thorn_Calculus/Thorn_Calculus-Processes.thy
- Isabelle/Thorn_Calculus/Thorn_Calculus-Semantics-Synchronous.thy
- Isabelle/Transition_Systems-New/ROOT
> Make various small changes

- Isabelle/Ouroboros_Examples/Chain_Selection_Property.thy
- Isabelle/Ouroboros_Examples/ROOT
- Isabelle/Ouroboros_Examples/document/root.tex
- Isabelle/ROOTS
> Introduce proof of the chain selection property

- Isabelle/Ouroboros/Ouroboros_BFT_Implementation.thy
- Isabelle/Ouroboros/ROOT
- Isabelle/Ouroboros/document/root.tex
- Isabelle/ROOTS
> Implement the Ouroboros BFT protocol

- Isabelle/Ouroboros/Finite_Map_Extras.thy
- Isabelle/Ouroboros/Ouroboros_Praos_Implementation.thy
- Isabelle/Ouroboros/ROOT
- Isabelle/Ouroboros/document/root.tex
- Isabelle/ROOTS
> Implement the Ouroboros Praos protocol

- Isabelle/Ouroboros/Genesis/Chain_Selection_Density_Equivalence/Blocks.thy
- Isabelle/Ouroboros/Genesis/Chain_Selection_Density_Equivalence/Chains.thy
- Isabelle/Ouroboros/Genesis/Chain_Selection_Density_Equivalence/Proof.thy
- Isabelle/Ouroboros/Genesis/Chain_Selection_Density_Equivalence/Protocol_Parameters.thy
- Isabelle/Ouroboros/Genesis/Chain_Selection_Density_Equivalence/Timing.thy
- Isabelle/Ouroboros/Genesis/Chain_Selection_Density_Equivalence/document/root.bib
- Isabelle/Ouroboros/Genesis/Chain_Selection_Density_Equivalence/document/root.tex
- Isabelle/Ouroboros/ROOT
- Isabelle/Ouroboros/document/root.tex
- Isabelle/ROOTS
> Formally prove the Genesis chain selection rule–Density rule equivalence

- Isabelle/Ouroboros/Ouroboros_Praos_Forwarding_Broadcasting_Equivalence.thy
- Isabelle/Ouroboros/Ouroboros_Praos_Implementation.thy
- Isabelle/Ouroboros/ROOT
> Formally prove the forwarding–broadcasting network equivalence for Ouroboros Praos

- Isabelle/Transition_Systems-New/ROOT
> Remove spurious dependency on `HOL-Library`

- Isabelle/Thorn_Calculus/Thorn_Calculus-Semantics-Asynchronous.thy
> Restore `Thorn_Calculus-Semantics-Asynchronous`
